[build]
rustflags = [
    "--codegen", "force-frame-pointers=yes",
    "--cfg", "tokio_unstable",
]

[target.'cfg(all(target_os = "linux", any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")))']
rustflags = [
    "--codegen", "force-frame-pointers=yes",
    "--cfg", "tokio_unstable",
    "--cfg", "tokio_taskdump",
]
